# provide a name if you wish
# name: btlz-test


networks:
  postgres-net:
    driver: bridge

volumes:
  postgres-vol:
    driver: local

services:

  postgres:
    container_name: postgres

    image: postgres:16.1-alpine

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - postgres-vol:/var/lib/postgresql/data

    networks:
      - postgres-net

    expose:
      - 5432

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped


  app:
    container_name: app

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      NODE_ENV: production
      WB_API_KEY: ${WB_API_KEY}
      GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
      GOOGLE_TOKEN: ${GOOGLE_TOKEN}

    ports:
      - "${APP_PORT:-3000}:3000"

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-net

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

    restart: unless-stopped
